<Project>
  <PropertyGroup>
      <BaseOutputPath>$(MSBuildThisFileDirectory)/build/bin/</BaseOutputPath>
      <BaseIntermediateOutputPath>$(MSBuildThisFileDirectory)/build/obj/</BaseIntermediateOutputPath>
      <BaseArtifactsPath>$(MSBuildThisFileDirectory)/build/obj/</BaseArtifactsPath>
  </PropertyGroup>
</Project>