namespace ABP.Domain.Entities;

/// <summary>
/// Object representing booking of a room. 
/// </summary>
public class Booking { 
    private readonly string _id;
    private Room _room;
    private DateTime _startTime;
    private DateTime _endTime;

    /// <summary>
    /// Returns readonly id of the booking. 
    /// </summary>
    /// <value>An Id of the booking.</value> 
    public string Id => _id;

    /// <summary>
    /// Gets and sets not null room.
    /// </summary>
    /// <value>Booked room.</value>
    public Room Room { 
        get => _room;
        set {
            if (value is null)
                throw new ArgumentException("Room must be not null.");
            _room = value;
        }
    }

    /// <summary>
    /// Gets and sets booking start time.
    /// </summary>
    /// <value>Start time of booking.</value>
    public DateTime StartTime {
        get => _startTime;
        set { 
            if (value >= _endTime)
                throw new ArgumentException("Start time must be lower than end time.");
            _startTime = value;
        }
    }

    /// <summary>
    /// Gets and sets booking end time.
    /// </summary>
    /// <value>End time of booking.</value>
    public DateTime EndTime {
        get => _endTime;
        set { 
            if (value <= _startTime)
                throw new ArgumentException("End time must be greater than start time.");
            _endTime = value;            
        }
    }

    /// <summary>
    /// Creates a new booking instance with autogenerated GUID.
    /// </summary>
    /// <param name="room">The booked room.</param>
    /// <param name="startTime">Booking start time.</param>
    /// <param name="endTime">Booking end time.</param>
    public Booking (Room room, DateTime startTime, DateTime endTime) { 
        ArgumentNullException.ThrowIfNull(room);

        _id = Guid.NewGuid().ToString();
        _room = room;
        
        if (startTime.Date == endTime.Date && startTime < endTime) {
            _startTime = startTime;
            _endTime = endTime;
        } 
    }

    /// <summary>
    /// Check if 2 bookings overlaps.
    /// </summary>
    /// <param name="other">Other booking object.</param>
    /// <returns>Whether 2 bookings overlaps.</returns>
    public bool Overlaps (Booking other) { 
        if (this.Room != other.Room) return false;
        
        if (this.StartTime < other.EndTime && this.EndTime <= other.StartTime ||
            this.EndTime > other.StartTime && this.StartTime >= other.EndTime) return false;
        else return true;
    }
}