using System.Text.Unicode;

namespace ABP.Domain.Entities;

/// <summary>
/// Provides an entity of a room.
/// </summary>
public class Room : IEquatable<Room>{ 
    private readonly string _id;
    private string _name;
    private int _capacity;
    private decimal _basePrice;
    private readonly List<Service> _services = [];

    /// <summary>
    /// Returns readonly id of the room. 
    /// </summary>
    /// <value>An Id of the room.</value> 
    public string Id => _id;

    /// <summary>
    /// Gets and sets not empty name of the room.
    /// </summary>
    /// <value>Name of the room.</value>
    public string Name { 
        get => _name;
        set {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException("Name must be not empty.");
            _name = value;
        } 
    }

    /// <summary>
    /// Gets and sets positive capacity of the room.
    /// </summary>
    /// <value>Capacity of the room.</value>
    public int Capacity { 
        get => _capacity; 
        set {
            if (value <= 0) 
                throw new ArgumentException("Capacity must be a positive number.");
            _capacity = value;
        } 
    }

    /// <summary>
    /// Gets and sets positive base price of the room rent.
    /// </summary>
    /// <value>Base price of the room rent.</value>
    public decimal BasePrice {
        get => _basePrice;
        set {
            if (value <= 0)
                throw new ArgumentException("Base price must be a positive number.");
            _basePrice = value;
        } 
    }

    /// <summary>
    /// Gets collection of services the room provides.
    /// </summary>
    /// <value>List of available services.</value>
    public List<Service> Services => _services;

    /// <summary>
    /// Creates a new room instance with autogenerated GUID.
    /// </summary>
    /// <param name="name">Name of the room.</param>
    /// <param name="capacity">Capacity of the room.</param>
    /// <param name="basePrice">Price of the room.</param>
    /// <param name="services">List of services available for this room.</param>
    public Room (string name, int capacity, decimal basePrice, List<Service> services) {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        
        _id = Guid.NewGuid().ToString();
        _name = name;
        Capacity = capacity;
        BasePrice = basePrice;
        Services.AddRange(services);
    }

    /// <summary>
    /// Copy constructor.
    /// </summary>
    /// <param name="other">Room to be copied.</param>
    public Room (Room other) { 
        _id = other._id;
        _name = other._name;
        _capacity = other._capacity;
        _basePrice = other._basePrice;
        _services.AddRange(other._services.Select(s => new Service(s)));
    }
    
    /// <summary>
    /// Value equality check.
    /// </summary>
    /// <param name="room">Another room, examined for equality.</param>
    public bool Equals(Room? room) {
        if (room is null) return false;
        return room._id == _id && 
            room._name == _name &&
            room._basePrice == _basePrice && 
            room._capacity == _capacity &&
            room._services.All(s => _services.Contains(s)) &&
            room._services.Count == _services.Count;
    }

    public override bool Equals(object? obj) {
        if (obj is not Room) return false;
        else return Equals(obj as Room);
    }

    public override int GetHashCode() => 
        HashCode.Combine(_id, _capacity, _name);
}