namespace ABP.Domain.Entities;

/// <summary>
/// Provides an entity of service providen by certain room.
/// </summary>
public class Service { 
    private readonly string _id;
    private string _name;
    private decimal _price;

    /// <summary>
    /// Returns readonly id of the service. 
    /// </summary>
    /// <value>An Id of the service.</value> 
    public string Id => _id;

    /// <summary>
    /// Gets and sets not empty name of the service.
    /// </summary>
    /// <value>Name of the service</value>
    public string Name { 
        get => _name;
        set {
            if (string.IsNullOrWhiteSpace(value))
                throw new ArgumentException("Name must be not empty.");
            _name = value;
        } 
    }

    /// <summary>
    /// Gets and sets positive price of the service.
    /// </summary>
    /// <value>Price of the service.</value>
    public decimal Price {
        get => _price;
        set {
            if (value <= 0)
                throw new ArgumentException("Price must be a positive number.");
            _price = value;
        } 
    }

    /// <summary>
    /// Creates a new service instance with autogenerated GUID.
    /// </summary>
    /// <param name="name">Name of the service.</param>
    /// <param name="price">Price of the service</param>
    public Service (string name, decimal price) {
        ArgumentException.ThrowIfNullOrWhiteSpace(name);
        
        _id = Guid.NewGuid().ToString();
        _name = name;
        Price = price;
    }

    /// <summary>
    /// Overrided equality, compared by fields.
    /// </summary>
    /// <param name="obj">Another instance this compared with.</param>
    /// <returns>`true`, if are equal.</returns>
    public override bool Equals(object? obj)
    {
        if (obj is null) return false;
        return Id == (obj as Service)?.Id && Name == (obj as Service)?.Name && Price == (obj as Service)?.Price;
    }
}