using ABP.Domain.Exceptions;

namespace ABP.Domain.Entities;

/// <summary>
/// Provides an entity of service providen by certain room.
/// </summary>
public record Service : IEquatable<Service>
{

    /// <summary>
    /// Gets id of the service. 
    /// </summary>
    /// <value>An Id of the service.</value> 
    public string Id { get; init; } = null!;

    /// <summary>
    /// Gets name of the service.
    /// </summary>
    /// <value>Name of the service</value>
    public string Name { get; init; }

    /// <summary>
    /// Gets price of the service.
    /// </summary>
    /// <value>Price of the service.</value>
    public decimal Price { get; init; }

    /// <summary>
    /// Creates a new service instance with autogenerated GUID.
    /// </summary>
    /// <param name="name">Name of the service.</param>
    /// <param name="price">Price of the service</param>
    public Service(string name, decimal price) :
        this(Guid.NewGuid().ToString(), name, price)
    { }

    /// <summary>
    /// Creates a new service instance with autogenerated GUID.
    /// </summary>
    /// <param name="id">Id of the service.</param>
    /// <param name="name">Name of the service.</param>
    /// <param name="price">Price of the service</param>
    public Service(string id, string name, decimal price)
    {
        if (string.IsNullOrWhiteSpace(id))
            throw new DomainRulesViolationException("Id of the service cannot be null");
        if (string.IsNullOrWhiteSpace(name))
            throw new DomainRulesViolationException("Name of the service cannot be null");
        if (price <= 0)
            throw new DomainRulesViolationException("Price of service must be positive.");

        Id = id;
        Name = name;
        Price = price;
    }

    /// <summary>
    /// Copy constructor.
    /// </summary>
    /// <param name="other">Service to be copied.</param>
    public Service(Service other)
    {
        Id = other.Id;
        Name = other.Name;
        Price = other.Price;
    }

    public override int GetHashCode() =>
        HashCode.Combine(Id);
}